INSERT INTO habit_images ("https://img.icons8.com/material-outlined/48/000000/pencil--v1.png")
INSERT INTO habit_images ("https://img.icons8.com/material-outlined/48/000000/brain--v1.png")
INSERT INTO habit_images ("https://img.icons8.com/windows/48/000000/broccoli.png")
INSERT INTO habit_images ("https://img.icons8.com/material-outlined/48/000000/dumbbell.png")
INSERT INTO habit_images ("https://img.icons8.com/ios/48/000000/sun--v1.png")
INSERT INTO habit_images ("https://img.icons8.com/material-outlined/48/000000/water.png")
INSERT INTO habit_images ("https://img.icons8.com/external-konkapp-detailed-outline-konkapp/48/000000/external-sweeping-hygiene-routine-konkapp-detailed-outline-konkapp.png")
INSERT INTO habit_images ("https://img.icons8.com/material-outlined/48/000000/money--v1.png")