INSERT INTO days (day,checked, habit_id) 
VALUES
('Monday', true,1),
('Tuesday',false, 1),
('Wednesday',false, 1),
('Thursday',false, 1),
('Friday',false, 1),
('Saturday',false, 1),
('Sunday',false, 1),
('Monday', true, 2),
('Tuesday',false, 2),
('Wednesday',false, 2),
('Thursday',false, 2),
('Friday',false, 2),
('Saturday',false, 2),
('Sunday',false, 2),
('Monday', true, 3),
('Tuesday',false, 3),
('Wednesday',false, 3),
('Thursday',false, 3),
('Friday',false, 3),
('Saturday',false, 3),
('Sunday',false, 3),
('Monday', true, 4),
('Tuesday',false, 4),
('Wednesday',false, 4),
('Thursday',false, 4),
('Friday',false, 4),
('Saturday',false, 4),
('Sunday',false, 4),
('Monday', true, 5),
('Tuesday',false, 5),
('Wednesday',false, 5),
('Thursday',false, 5),
('Friday',false, 5),
('Saturday',false, 5),
('Sunday',false, 5)