
INSERT INTO journals (scale, title, entry, choice, student_id)
VALUES
(7, 'Beky Fields', 'Today, Becky and I went to the lake and lay our heads on the green grass for hours until sundown. It was a mesmerizing experience. Becky dragged me there saying it would help wind down after a long day and I''m happy I came. I hope my friends from my hometown Sidney can one day share that experience with us here. I have also rehearsed for the upcoming play for the family celebration this Sunday. I hope I don''t stutter like last time.', './icons/friends.png', 1),
(3, 'Betrayal', 'I found my bag on the floor with all its contents thrown across the hallway. The worst part was Becky was standing next to my stuff with a smug look on her face. She looked like she finally won but I don''t understnad what she could''ve won. Did she get close to me just so she could embarrass me in front of the whole school. She never seemed like she would do that to me. I know she did that to other people but I''ve known her for years. I wanted to ask why she did that but I knew I would just look pathetic so I grabbed my stuff and ran off. I cried for two nights straight but I still showed up to school. I can''t let her think she won. I''m never talking to her again!!! ', './icons/mental-health.png', 1),
(8, 'Right Before Bed', 'My eyes are getting heavier tonight. I should sleep soon. It''s funny how I always think I have nothing to say but once I play with the start of ideas, it all starts to come down like rain. I needed this. To know I still have it in me. If I were to ever lose this part of myself… I''m not sure how I''d take that. For sure, I would feel so sad and so alone. Lost even. Writing is another love of mine. Writing is a form of looking in the mirror. Like drawing a figure. It is the drawing of one''s soul. Of one''s subconscious. Perhaps if you write the cusp of one''s soul and draw it out like a thread from the tangle of nothingness. And perhaps soon it can become poetry.', './icons/mental-health.png', 1),
(4, 'Meditation Rock', 'From the other side of the stream, there is an orange-ish, grayish rock that I can get to only by hopping stone to stone. This is my thinking rock. It''s just big enough for me to sit on and cross my legs. From there, I can meditate or just look at the water. I''ve meditated there three times, breathing steadily as I listen to the babbling water course next to me on either side of the river stone. I''m sitting on the rock now, as I write. And even though I''m not meditating, this rock makes me feel calm.
When I meditate, the water seems to guide me toward thoughtlessness, toward an empty mind, devoid of all but the sound of water. It rushes over the rocks, making it bubble and froth, but becomes calm again soon. After I open my eyes, the world seems kind of bluish Like the painting my parents have in the living room, blued by years of exposure to the sun. All color but blue is faded out, giving everything a surreal feeling. I could see this stream and forest as a painting on my living room wall, blued by the sun.', './icons/mental-health.png', 1),
(6, 'Fidning A Balance', 'Life at the Mountain School is rougher. I don''t yet have the spiritual capability or possess the physical strength for life in Vermont''s winter. I can love the season''s visual aspect, but I am in no way prepared for snowshoeing up hills and pushing myself to the top. The sense of time here is different and more beautiful. Not only am I allowed to admire the sunrise and look closely at the trees but I am expected to. Managing homework, in terms of time constraints, is still a challenge. But the challenge now is balancing school work with the outdoors, not schoolwork with more schoolwork. I have seen few sunrises but have had to rush onward to arrive at school in time for some sort of meeting or other. Now, I can stop for a few moments just to stare at the skys. That''s the real difference between the Mountain School and Sidney living.', './icons/mental-health.png', 1)



