INSERT INTO emojis (name, icon, description, affirmation)
VALUES 
('Anxious', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/confounded-face_1f616.png', 'This emoji represents anxiety. Anxiety can make you feel scared, nervous or worried about a future event.', 'Say to yourself: Anxiety might make me feel uncomfortable but I am in charge of my mind and body.'),
('Woozy', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/woozy-face_1f974.png', 'This emoji represents nausea. A feeling like you things are moving around you quickly, and you feel as if youre getting sick. This can sometimes be caused by anxiety.', 'Try to do some breathing exercise and say: Im going to focus on things I love to get me through this. I will be OK.'),
('Angry', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/angry-face_1f620.png', 'This emoji represents anger. You may be struggling with or frustrated about things beyond your control.', 'Its okay to be angry. You do such a great job of not giving up even if something is difficult for you.'),
('Stressed', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/persevering-face_1f623.png', 'This emoji represents stress. You may feel worried or uncomfortable about something.', 'Your feelings are valid, but dont forget that you are kind and capable!'),
('Embarrassed', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/flushed-face_1f633.png', 'This emoji represents feeling embarrassed. Sometimes when you feel embarrassed, your face might feel warm and your stomach will hurt.', 'Everyone has a moment of embarrassment, but we sometimes think much more of it than others ever do. You are so much more than that moment!'),
('Neutral', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/neutral-face_1f610.png', 'This emoji represents feeling neutral. You dont feel happy or sad right now.', 'Its okay to not have your emotions out on display. Keep in mind, you have a beautiful smile and you should share it.'),
('Irritable', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/face-with-steam-from-nose_1f624.png', 'This emoji represents irritability. Little problems probably feel like big problems.', 'Try to do some mindfulness meditation to help you calm yourself. Say to yourself: I will have an amazing day.'),
('Annoyed', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/face-with-rolling-eyes_1f644.png', 'This emoji represents annoyance. Little problems probably feel like big problems.', 'Try to do some mindfulness meditation to help you calm yourself. Say to yourself: I will have an amazing day.'),
('Anti-social', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/face-without-mouth_1f636.png', 'This emoji represents anti-social. That means you dont feel like talking to other people today.', 'People around you care about you, but it is okay to take some time to yourself and recharge.'),
('Pensive', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/pensive-face_1f614.png', 'This emoji represents being pensive. Pensive means youve been in your head most of the day thinking about different things.', 'Youve done a great job being reflective today. Dont be afraid to share reflections with loved ones!'),
('Disappointed','https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/disappointed-face_1f61e.png', 'This emoji represents disappointment. You were looking forward to something today and it didnt happen or wasnt what you expected. These things happen and its okay to be disappointed.', 'Dont let disappointment control how you feel about it and ruin your day. Say: I choose my own attitude and I choose to be happy!'),
('Fearful', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/fearful-face_1f628.png', 'This emoji represents fear. You are feeling scared today, like something is going to happen.', 'Try to remind yourself: I am safe, in my body and at this moment.');



