INSERT INTO emojis (name, icon, description, affirmation)
VALUES 
('Anxious', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/confounded-face_1f616.png', 'This emoji represents anxiety. A feeling like something bad will happen', 'Focus on what you can control. Do those things well.'),
('Woozy', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/woozy-face_1f974.png', 'This emoji represents woozy. A feeling like you things are moving around you quickly, and youre getting sick trying to keep up.', 'Focus on what you can control. Do those things well.'),
('Angry', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/angry-face_1f620.png', 'This emoji represents anger. An intense feeling usually caused by something.', 'Its okay to be angry. Take some time doing something you like.'),
('Stressed', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/persevering-face_1f623.png', 'This emoji represents stress. Stress can be caused when you feel like you have too much to do.', 'Try not to focus on all the things you have to do. Pick a few things to do at a time.'),
('Embarrassed', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/flushed-face_1f633.png', 'This emoji represents feeling embarrassed. Sometimes when you feel embarrassed, your face might feel warm and your stomach will hurt.', ' This is normal! Everyone feels like that sometimes. Go do something you love or talk to someone you love about it.'),
('Neutral', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/neutral-face_1f610.png', 'This emoji represents feeling neutral. You dont feel happy or sad right now.', 'Its okay to not have your emotions out on display. Keep in mind, you have a beautiful smile and you should share it.'),
('Irritable', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/face-with-steam-from-nose_1f624.png', 'This emoji represents irritability. Little problems probably feel like big problems.', 'People around you care about you. Reach out to family or friends to feel a bit better.'),
('Annoyed', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/face-with-rolling-eyes_1f644.png', 'This emoji represents annoyance. Little problems probably feel like big problems.', 'People around you care about you. Reach out to family or friends to feel a bit better.'),
('Anti-social', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/face-without-mouth_1f636.png', 'This emoji represents anti-socialness. That means you dont feel like talking to other people today.', 'People around you care about you, but it is okay to take some time to yourself and recharge.'),
('Pensive', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/pensive-face_1f614.png', 'This emoji represents being pensive. Pensive means youve been in your head most of the day thinking about different things.', 'Youve done a great job being reflective today. Dont be afraid to share reflections with loved ones!'),
('Disappointed','https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/disappointed-face_1f61e.png', 'This emoji represents disappointment. You were looking forward to something today and it didnt happen or wasnt what you expected.', 'These things happen and its okay to be disappointed. Take the time you need to feel better about it.'),
('Fearful', 'https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/openmoji/292/fearful-face_1f628.png', 'This emoji represents fearfulness. You are feeling fearful today, like something is going to happen.', 'Try and join a loved one and be with them. They will remind you that you are safe and there is nothing to worry about.');



